config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  resources :designmodels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/designmodel.rb
class Designmodel < ApplicationRecord
  has_many :tools, inverse_of: :designmodel
  accepts_nested_attributes_for :tools
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :designmodel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/designmodels_controller.rb
class DesignmodelsController < ApplicationController
  before_action :set_designmodel, only: [:show, :edit, :update, :destroy]

  # GET /designmodels
  # GET /designmodels.json
  def index
    @designmodels = Designmodel.all
  end

  # GET /designmodels/1
  # GET /designmodels/1.json
  def show
  end

  # GET /designmodels/new
  def new
    @designmodel = Designmodel.new
    
  end

  # GET /designmodels/1/edit
  def edit
  end

  # POST /designmodels
  # POST /designmodels.json
  def create

    @designmodel = Designmodel.new(designmodel_params)


    respond_to do |format|
      if @designmodel.save
        format.html { redirect_to @designmodel, notice: 'Designmodel was successfully created.' }
        format.json { render :show, status: :created, location: @designmodel }
      else
        format.html { render :new }
        format.json { render json: @designmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designmodels/1
  # PATCH/PUT /designmodels/1.json
  def update
    respond_to do |format|
      if @designmodel.update(designmodel_params)
        format.html { redirect_to @designmodel, notice: 'Designmodel was successfully updated.' }
        format.json { render :show, status: :ok, location: @designmodel }
      else
        format.html { render :edit }
        format.json { render json: @designmodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designmodels/1
  # DELETE /designmodels/1.json
  def destroy
    @designmodel.destroy
    respond_to do |format|
      format.html { redirect_to designmodels_url, notice: 'Designmodel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designmodel
      @designmodel = Designmodel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designmodel_params
      params.require(:designmodel).permit(:title, :description,tools_attributes: [:tool_name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designmodels_helper.rb
module DesignmodelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/designmodels/_form.html.erb
<%= simple_form_for(@designmodel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="tools">
    <%= f.simple_fields_for :tools do |t| %>
      <%= render "tool_fields" , f: t %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "Add" , f, :tools  %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/designmodels/_tool_fields.html.erb
<div class="nested-fields">
  <%= f.input_field :tool_name %>
  <%= link_to_remove_association(f) do %>
    <i>Remove</i>
  <%end%>
</div>

app/views/designmodels/edit.html.erb
<h1>Editing Designmodel</h1>

<%= render 'form', designmodel: @designmodel %>

<%= link_to 'Show', @designmodel %> |
<%= link_to 'Back', designmodels_path %>

app/views/designmodels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designmodels</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designmodels.each do |designmodel| %>
      <tr>
        <td><%= designmodel.title %></td>
        <td><%= designmodel.description %></td>
          <% for tool in designmodel.tools %>
          <td><%= tool.tool_name %></td>
          <% end %>

        <td><%= link_to 'Show', designmodel %></td>
        <td><%= link_to 'Edit', edit_designmodel_path(designmodel) %></td>
        <td><%= link_to 'Destroy', designmodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designmodel', new_designmodel_path %>

app/views/designmodels/new.html.erb
<h1>New Designmodel</h1>

<%= render 'form', designmodel: @designmodel %>

<%= link_to 'Back', designmodels_path %>

app/views/designmodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @designmodel.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @designmodel.description %>
</p>
<% for tool in @designmodel.tools %>
  <p><%= tool.tool_name %></p>
<% end %>
<%= link_to 'Edit', edit_designmodel_path(@designmodel) %> |
<%= link_to 'Back', designmodels_path %>

app/views/home/index.html.erb
<h1>Home</h1>
<%= link_to "Sign out" , destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Design</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>